#!/bin/sh

BRANCH=$(git rev-parse --abbrev-ref HEAD 2>/dev/null)
if [[ $? -ne 0 || -z $BRANCH ]]; then
    exit 0
fi
REGEX="(^(IOTSERVERS|ROB)-[0-9]+-[a-z\-]*|^HOTFIX-(IOTSERVERS|ROB)-[0-9]+-[a-z\-]*|^release-[0-9]+.[0-9]+.[0-9]+)"

if [[ $BRANCH == "develop" || $BRANCH == "master" ]]; then
  echo "You can not commit to $BRANCH"
  exit 1
fi

if ! [[ $BRANCH =~ $REGEX ]]; then
  echo "Your commit was rejected due to branching name"
  echo "Please rename your branch with $REGEX syntax"
  exit 1
fi
